version: "3.8"
services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo-6191
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - testreactpro22_6191-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - testreactpro22_6191_net
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2
  vault:
    image: vault:1.13.3
    container_name: vault-6191
    ports:
      - "8200:8200"
    environment:
        VAULT_SERVER: "http://127.0.0.1:8200"
        VAULT_DEV_ROOT_TOKEN_ID: vault-geppetto-2021
    cap_add:
      - IPC_LOCK
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-6191
    container_name: authproxy-6191
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - gcam
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-6191
    container_name: securitymanager-6191
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  systemcredentialmanager:
    build: ../../../application/services/default_services/systemcredentialmanager
    image: systemcredentialmanager-6191
    container_name: systemcredentialmanager-6191
    ports:
      - "8005:8005"
    env_file: .env
    depends_on:
      - mongo
      - vault
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  gepfilemanager:
    build: ../../../application/services/default_services/gepfilemanager
    image: gepfilemanager-6191
    container_name: gepfilemanager-6191
    ports:
      - "3015:3015"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  gcam:
    build: ../../../application/services/default_services/gcam
    image: gcam-6191
    container_name: gcam-6191
    ports:
      - "8007:8007"
    env_file: .env
    depends_on:
      - mongo
      - vault
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-6191
    container_name: apigateway-6191
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - authproxy
      - securitymanager
      - systemcredentialmanager
      - systementry
      - employees

    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch-6191
    restart: always
    environment:
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0
      - xpack.security.enrollment.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 262144
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - testreactpro22_6191_net

  kibana:
    image: kibana:8.13.0
    container_name: kibana-6191
    restart: always
    ports:
      - 5601:5601
    expose:
      - "5601"
    networks:
      - testreactpro22_6191_net
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  fluentd:
    image: fluentd-6191
    build: ../../../application/services/default_services/fluentd/fluend
    volumes:
      - ../../../application/services/default_services/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    restart: always
    container_name: fluentd-6191
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - testreactpro22_6191_net


  systementry: 
    build: ../../../application/services/custom_services/systementry
    image: systementry-6191
    container_name: systementry-6191
    ports: 
      - 8026:8026
    env_file: .env
    depends_on:
      - mongo
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  employees: 
    build: ../../../application/services/custom_services/employees
    image: employees-6191
    container_name: employees-6191
    ports: 
      - 8027:8027
    env_file: .env
    depends_on:
      - mongo
    networks:
      - testreactpro22_6191_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2


volumes:
  testreactpro22_6191-volume:
    driver: local
  elasticsearch:
networks:
  testreactpro22_6191_net:
    external: true
